// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "cellar": Application User Types
//
// Command:
// $ goagen
// --design=github.com/whithajess/golang-goa-api/design
// --out=$(GOPATH)/src/github.com/whithajess/golang-goa-api
// --version=v1.3.1

package app
